baseURL = "http://localhost:3000/rave-web"
title = "Rave Movie"

theme = "Puppet"

copyright = ""
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/78#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "list"
url = "/list/"
weight = 10
[[menu.main]]
identifier = "trending"
name = "Trending"
url = "/series/trending/"
weight = 0
[[menu.main]]
identifier = "request"
name = "request"
url = "/request/"
weight = 50
[[menu.main]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/synerize"
weight = 100


[params]
author = "Levi"
description = "Made in 💜 By Levi"
keywords = "movie,series,rave"
img_home = "https://www.themoviedb.org/t/p/original/yF1eOkaYvwiORauRCPWznV9xVvi.jpg"
img_404 = "img/404-bg.jpg"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/home-bg.jpg"
bio = "a personal website"

# See https://giscus.app/
[params.giscus]
enable = true
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
